version: "3"

services:
  app1:
    build: .
    container_name: app_sip_1
    ports:
      - 3000:3000
    environment:
      port: 3000
      VUE_APP_WS_SERVER: wss://devsip.vbeecore.com:65443
      VUE_APP_AOR: sip:10001@devsip.vbeecore.com
      VUE_APP_PASS: 1234
      VUE_APP_USER: 10001
    volumes:
      - ./:/app

  app2:
    build: .
    container_name: app_sip_2
    ports:
      - 3001:3001
    environment:
      port: 3001
      VUE_APP_WS_SERVER: wss://devsip.vbeecore.com:65443
      VUE_APP_AOR: sip:10000@devsip.vbeecore.com
      VUE_APP_PASS: 1234
      VUE_APP_USER: 10000
    volumes:
      - ./:/app
